sudo: false
language: python
matrix:
  include:
  - name: Python 2.7 Unit Test
    python: '2.7'
  - name: Python 3.4 Unit Test
    python: '3.4'
  - name: Python 3.5 Unit Test
    python: '3.5'
  - name: Pytnon 3.6 Unit Test
    python: '3.6'
  - name: Python 3.7 Unit Test
    python: '3.7'
    dist: xenial
    sudo: true
script: tox
install: pip install tox-travis codecov
deploy:
  skip_existing: true
  provider: pypi
  user: dgarana
  password:
    secure: U1kvvc/5KKVdA6l7I+yCNbXJjHhEkq3Jh9UMmAC15TzSrCf+YwHXKhy8g/Tigxl0T3Uxo+14/ac0yl4Z8g0Vx3S0q9/MvA7KEV3sywlVnjp2Dp3owxJ04rVCPPCEw50ET6/zR0WwhVlcCahWL2H7WNu5jA7+Ui8KNm7Kcp9+8Ed/QuoToG7oRw8KsgDV7bUigaaFLzthhaA6KMl1xJf0Z4LZhEaDnvHUPzOa9+blswEURKnhAFbmphcYLt7cWDtro2r98Jocc4Go4BP4uPNzWa/5RFtW1G/kH7O/UKDedCSrHOt/8jnO+gLSncxow70KKeqtCnRKJVdxRGta6n4CBCYOQkMU86UQBjEZip5kTWFLenXJocm9NpvUkRZyW0f8jq7Mfl89Zv9H/63HWdTiQrgDMGpt71aU+yBsLeFxbphpbHZN+h8nJuvJDn1iZq6Of4qHo+oV5wRJJ27QvcFc76+tqqOeU72TKt4S8EXt1n8rZv5Ax2uJlCT5kSu37b+ASyRh77yVQxcq2J3ZoxKDqPu206wKV2j9pHp5DnzRLGI8cd3XEjY5eHvRRSm9FD9wCb2Gg7gBOL/cAqZ3UwuI5EZ1xOrtDkEX7EEi/ZF58AzNkWG07KWXv5SFMkrzFxKequYA8NADnQ76cHLintc8qxEqDJ4lYVGpYirvpcL4chc=
  on:
    tags: true
