sudo: false
language: python
language: python
matrix:
  include:
  - name: "Python 2.7 Unit Test"
    python: "2.7"
  - name: "Python 3.4 Unit Test"
    python: "3.4"
  - name: "Python 3.5 Unit Test"
    python: "3.5"
  - name: "Pytnon 3.6 Unit Test"
    python: "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
  - name: "Python 3.7 Unit Test"
    python: "3.7"
    dist: xenial
    sudo: true
script: tox
install: pip install tox-travis codecov
